using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;


public class EnemyDist : MonoBehaviour
{
    public NavMeshAgent Agent;
    
    public Transform player;
    public LayerMask whatIsGround, whatIsPlayer;
    //patrolling
    public Vector3 walkpoint;
    bool walkPointSet;
    public float walkPointRange;
    //attacking
    public int ForceUP;
    public GameObject Firepoint;
    public int ForceForward;
    public float timeBetweenAttacks;
    bool alreadyAttacked;
    public GameObject proyectil;
    //states
    public float sightRange, attackRange;
    public bool playerInSightRange, playerInAttackRange;
    private void Awake()
    {
        player = GameObject.Find("perso").transform;
        Agent = GetComponent<NavMeshAgent>();

    }
    private void Update()
    {
        //check for sight attack range
        playerInSightRange = Physics.CheckSphere(transform.position, sightRange, whatIsPlayer);
        playerInAttackRange = Physics.CheckSphere(transform.position, attackRange, whatIsPlayer);
        if (!playerInSightRange && !playerInAttackRange) Patroling();
        if (playerInSightRange && !playerInAttackRange) chase();
        if (playerInAttackRange && playerInSightRange) AttackPlayer();
                
    }
    private void Patroling()
    {
        if (!walkPointSet) SearchWalkPoint();
        if (walkPointSet)
            Agent.SetDestination(walkpoint);
        Vector3 distanceToWalkPoint = transform.position - walkpoint;
        //walkpoint reached
        if (distanceToWalkPoint.magnitude < 1f)
        {
            walkPointSet = false;
        }
    }
    private void SearchWalkPoint()
    {
        //calculate random point in range
        float randomZ = Random.Range(-walkPointRange, walkPointRange);
        float randomX = Random.Range(-walkPointRange, walkPointRange);
        walkpoint = new Vector3(transform.position.x + randomX, transform.position.y, transform.position.z + randomZ);
        if (Physics.Raycast(walkpoint, -transform.up, 2f, whatIsGround))
        {
            walkPointSet = true;
        }
    }
    private void chase()
    {
        
        Agent.SetDestination(player.position);
    }
    private void AttackPlayer()
    {
        //make sure enemy doesn't move
        Agent.SetDestination(transform.position);
        Vector3 newPlayer = player.position;
        newPlayer.y = transform.position.y;
        transform.LookAt(newPlayer);
        if (!alreadyAttacked)
        {
            //attack
            Rigidbody rb = Instantiate(proyectil, Firepoint.transform.position, Quaternion.identity).GetComponent<Rigidbody>();
            
            rb.AddForce(transform.forward * ForceForward, ForceMode.Impulse);
            rb.AddForce(transform.up * ForceUP, ForceMode.Impulse);
            alreadyAttacked = true;
            Invoke(nameof(ResetAttack), timeBetweenAttacks);
            
        }
    }
    private void ResetAttack()
    {
        alreadyAttacked = false;
    }
    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, attackRange);
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(transform.position, sightRange);
    }



}
